%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\maxdesktop\MATLAB Drive\Lab Week 11\Question_4_Data\pasco_data.txt
%
% Auto-generated by MATLAB on 11-Nov-2020 15:57:32

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "DateAndTime", "Times", "Positionm", "Velocityms", "Accelerationms"];
opts.SelectedVariableNames = ["DateAndTime", "Times", "Positionm", "Velocityms", "Accelerationms"];
opts.VariableTypes = ["string", "datetime", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "DateAndTime", "InputFormat", "MM/dd/yyyy hh:mm:ss aa");

% Import the data
tbl = readtable("C:\Users\maxdesktop\MATLAB Drive\Lab Week 11\Question_4_Data\pasco_data.txt", opts);

%% Convert to output type
DateAndTime = tbl.DateAndTime;
Times = tbl.Times;
Positionm = tbl.Positionm;
Velocityms = tbl.Velocityms;
Accelerationms = tbl.Accelerationms;

%% Clear temporary variables
clear opts tbl