function [fitresult, gof] = createFit(f, A)
%CREATEFIT(F,A)
%  Create a fit.
%
%  Data for 'LOBF' fit:
%      X Input : f
%      Y Output: A
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Nov-2020 17:17:52


%% Fit: 'LOBF'.
[xData, yData] = prepareCurveData( f, A );

% Set up fittype and options.
ft = fittype( 'b1/((omega_0^2-omega_d^2)^2+b2*omega_d^2)', 'independent', 'omega_d', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.814284826068816 0.243524968724989 0.929263623187228];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'LOBF' );
h = plot( fitresult, xData, yData );
legend( h, 'A vs. f', 'LOBF', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'f', 'Interpreter', 'none' );
ylabel( 'A', 'Interpreter', 'none' );
grid on


