function [fitresult, gof] = createFit(mass, Nevents, err)
%CREATEFIT(MASS,NEVENTS,ERR)
%  Create a fit.
%
%  Data for 'untitled fit 8' fit:
%      X Input : mass
%      Y Output: Nevents
%      Weights : err
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Oct-2020 17:12:27


%% Fit: 'untitled fit 8'.
[xData, yData, weights] = prepareCurveData( mass, Nevents, err );

% Set up fittype and options.
ft = fittype( 'k * 1/((x^2 -  mz^2)^2 + mz^2 * wz^2)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = (xData < 60) | (xData > 120);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [99999999 80 3];
opts.Robust = 'Bisquare';
opts.StartPoint = [0.902716109915281 0.944787189721646 0.49086409246808];
opts.Upper = [Inf 100 7.5];
opts.Weights = weights;
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 8' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'Nevents vs. mass with err', 'Excluded Nevents vs. mass with err', '2 Muons LOBF', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'mass', 'Interpreter', 'none' );
ylabel( 'Nevents', 'Interpreter', 'none' );
grid on


