function [fitresult, gof] = createFit1(x, N, err)
%CREATEFIT1(X,N,ERR)
%  Create a fit.
%
%  Data for 'Fit to mass peak' fit:
%      X Input : x
%      Y Output: N
%      Weights : err
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Oct-2017 10:32:38


%% Fit: 'Fit to mass peak'.
[xData, yData, weights] = prepareCurveData( x, N, err );

% Set up fittype and options.
ft = fittype( 'a1+a2*x +a3*x^2 +c1*exp(-(x-c2)^2/(2*s^2))', 'independent', 'x', 'dependent', 'y' );
excludedPoints = (xData < 2.2) | (xData > 4);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf 3 0.005];
opts.StartPoint = [0.258064695912067 0.904880968679893 0.979748378356085 0.408719846112552 3.1 0.184816320124136];
opts.Upper = [Inf Inf Inf Inf 3.2 0.12];
opts.Weights = weights;
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fit to mass peak near 3 GeV' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'Nevents vs. mass with err', 'Excluded Nevents vs. mass with err', 'Fit to mass peak', 'Location', 'NorthEast' );
% Label axes
xlabel 'Lepton pair mass (GeV)'
ylabel 'Nevents per mass bin'
grid on


