function [fitresult, gof] = createFit(mass, Nevents, err)
%CREATEFIT(MASS,NEVENTS,ERR)
%  Create a fit.
%
%  Data for 'untitled fit 4' fit:
%      X Input : mass
%      Y Output: Nevents
%      Weights : err
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Oct-2020 16:42:51


%% Fit: 'LOBF'.
[xData, yData, weights] = prepareCurveData( mass, Nevents, err );

% Set up fittype and options.
ft = fittype( 'k * 1/((x^2 -  mz^2)^2 + mz^2 * wz^2)', 'independent', 'x', 'dependent', 'f' );
excludedPoints = (xData < 60) | (xData > 120);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.MaxIter = 300;
opts.Robust = 'Bisquare';
opts.StartPoint = [89.37 0.6892 0.7482];
opts.Weights = weights;
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', '2 electrons LOBF' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'Nevents vs. mass with err', 'Excluded Nevents vs. mass with err', '2 Electrons LOBF', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'mass', 'Interpreter', 'none' );
ylabel( 'Nevents', 'Interpreter', 'none' );
grid on


